services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:5001
    ports:
      - "3000:80"
    depends_on:
      - api
    restart: always
  seq:
    image: datalust/seq:2024.1
    ports:
      - "5341:80"
    environment:
      ACCEPT_EULA: Y
    restart: always
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      FRONTEND_ORIGIN: http://localhost:3000
      DB_HOST: db
      DB_PORT: ${POSTGRES_DB_PORT}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      SEQ_URL: http://seq:5341
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "${POSTGRES_DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data:
